=== alphagov/whitehall/public/configurable-document-type.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://whitehall-admin.publishing.service.gov.uk/configurable-document-type.schema.json",
  "$defs": {
    "validations": {
      "description": "List of rails validations to apply to properties, mapping to validators in the application. Keys must match available validators.",
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "attributes": {
              "description": "List of edition fields to validate, with this specific validator.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "on": {
              "description": "Validation context.",
              "type": "string",
              "enum": ["publish"]
            }
          },
          "additionalProperties": true
        }
      },
      "propertyNames": {
        "enum": [
          "embedded_contacts_exist",
          "length",
          "no_footnotes_allowed",
          "presence",
          "safe_html",
          "valid_internal_path_links",
          "social_media_links"
        ]
      }
    },
    "form_field": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "description": "Display name for the content block."
        },
        "description": {
          "type": "string",
          "description": "Description of the content block's purpose. Usually used for hint text."
        },
        "required": {
          "type": "boolean",
          "description": "Whether or not the form value is required"
        },
        "attribute_path": {
          "type": "array",
          "description": "The path of the active record attribute this field controls. For JSON attributes this may have multiple items",
          "items": {
            "type": "string"
          }
        },
        "block": {
          "type": "string",
          "description": "Identifier for a content block. Maps to a specific block class.",
          "enum": [
            "default_array",
            "default_date",
            "default_object",
            "default_string",
            "default_textarea",
            "govspeak",
            "default_select",
            "select_with_search_tagging",
            "ordered_select_with_search_tagging"
          ]
        },
        "fields": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "$ref": "#/$defs/form_field"
            }
          }
        },
        "translatable": {
          "description": "Determines whether or not the field's value can be translated for different locales",
          "type": "boolean"
        },
        "experimental": {
          "description": "When true, only renders the field if the configurable_document_types feature flag is enabled",
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "description": "List of options for select inputs.",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            },
            "required": ["label", "value"]
          }
        },
        "blank_option_label": {
          "type": "string",
          "description": "Text to display for the blank/default option in a select input."
        },
        "container": {
          "description": "The option container to be used in the select_with_search_tagging_block",
          "type": "string",
          "enum": [
            "alternative_format_providers",
            "detailed_guides",
            "ministerial_role_appointments",
            "organisations",
            "role_appointments",
            "roles",
            "statistical_data_sets",
            "topical_event_documents",
            "topical_events",
            "world_locations",
            "worldwide_organisations"
          ]
        },
        "size": {
          "type": "number",
          "description": "The number of items in an array field"
        },
        "add_another_button_text": {
          "type": "string",
          "description": "Text to display for the 'Add another' button in default_array block. If empty, it defaults to 'Add another'."
        }
      },
      "required": ["title", "block", "attribute_path", "translatable"],
      "additionalProperties": false
    },
    "block_attributes": {
      "type": "object",
      "description": "Map of content block attribute definitions (minimal schema).",
      "patternProperties": {
        ".*": { "$ref": "#/$defs/block_attribute" }
      },
      "additionalProperties": false
    },
    "block_attribute": {
      "type": "object",
      "description": "Minimal schema information for a single content block attribute.",
      "properties": {
        "type": {
          "type": "string",
          "description": "Data type for the content block. Should map to an active record type, with the exception of the object type.",
          "enum": ["string", "integer", "date", "array"]
        },
        "attributes": {
          "description": "For array types, defines the schema of each array item using the same minimal attribute format.",
          "$ref": "#/$defs/block_attributes"
        }
      },
      "required": ["type"],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": { "type": { "const": "array" } },
            "required": ["type"]
          },
          "then": {
            "properties": {
              "attributes": { "$ref": "#/$defs/block_attributes" }
            }
          },
          "else": {
            "not": {
              "required": ["attributes"]
            }
          }
        }
      ]
    }
  },
  "title": "Configurable Document Type",
  "description": "Schema for a configurable document type in Whitehall",
  "type": "object",
  "properties": {
    "key": {
      "type": "string",
      "pattern": "^[a-z_]*$",
      "description": "Unique identifier for the document type. This value is stored in the edition's configurable_document_type column."
    },
    "title": {
      "type": "string",
      "description": "Human-readable name for the document type, used in the admin interface."
    },
    "description": {
      "type": "string",
      "description": "A description of the document type's purpose and intended use."
    },
    "schema": {
      "type": "object",
      "description": "Defines the content structure for the document type. Each property represents a content block.",
      "properties": {
        "attributes": {
          "$ref": "#/$defs/block_attributes",
          "description": "Alternative to `properties`, defining content blocks with minimal schema information."
        },
        "validations": {
          "$ref": "#/$defs/validations"
        },
        "headings_from": {
          "type": "array",
          "description": "Array of content block names, from which to extract headings, used to generate the table of contents for the rendered document. Headings are sent to publishing API as part of the `details` hash.",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "forms": {
      "type": "object",
      "description": "Defines the content structure for the document type. Each property represents a content block.",
      "required": ["documents"],
      "properties": {
        "documents": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "fields": {
              "type": "object",
              "description": "Fields/content blocks for the document, each with its own schema.",
              "patternProperties": {
                ".*": {
                  "$ref": "#/$defs/form_field"
                }
              }
            }
          }
        }
      },
      "additionalProperties": {
        "type": "object",
        "required": ["fields"],
        "description": "Definition of a group of form fields to group.",
        "properties": {
          "dynamic": {
            "type": "boolean",
            "description": "Determines if the field should have a tab generated dynamically"
          },
          "label": {
            "type": "string",
            "description": "Text to display as the label for the group of fields. Shown on the tab in the admin interface."
          },
          "fields": {
            "type": "object",
            "description": "Fields/content blocks for this form, each with its own schema.",
            "patternProperties": {
              ".*": {
                "$ref": "#/$defs/form_field"
              }
            }
          }
        }
      }
    },
    "presenters": {
      "type": "object",
      "description": "Defines how content blocks map to publishing API presenters and formats.",
      "properties": {
        "publishing_api": {
          "type": "object",
          "properties": {
            "details": {
              "type": "object",
              "description": "Mapping of schema attributes to their respective publishing API details formats.",
              "patternProperties": {
                ".*": {
                  "type": "string",
                  "description": "The format to use for the content block when presenting to the Publishing API.",
                  "enum": [
                    "govspeak",
                    "rfc3339_date",
                    "image",
                    "raw",
                    "social_media_links"
                  ]
                }
              },
              "propertyNames": {
                "type": "string",
                "description": "Attribute to be included in the presenter payload. Must match an existing attribute defined in the schema."
              }
            },
            "links": {
              "description": "The builder methods to use for the links object when presenting to the Publishing API.",
              "type": "array",
              "items": {
                "type": "string",
                "description": "The builder methods to use for populating the links object when presenting to the Publishing API.",
                "enum": [
                  "ministerial_role_appointments",
                  "topical_events",
                  "world_locations",
                  "organisations",
                  "worldwide_organisations",
                  "government"
                ]
              }
            }
          },
          "additionalProperties": false,
          "required": ["details", "links"]
        }
      },
      "additionalProperties": false,
      "required": ["publishing_api"]
    },
    "settings": {
      "type": "object",
      "description": "A list of configurations to enable certain edition behaviours.",
      "properties": {
        "base_path_prefix": {
          "type": ["string", "null"],
          "description": "URL prefix for where documents of this type are published. E.g. /government/history. Can be set to null for child document types that use their parent's base path prefix.",
          "pattern": "^\/[\/.a-zA-Z0-9-]+$",
          "x-error": {
            "pattern": "string at `settings/base_path_prefix` is not a valid URL"
          }
        },
        "configurable_document_group": {
          "type": "string",
          "description": "Optional grouping for document types. Used for categorisation in the admin interface, including search filters. Typically matches the `publishing_api_schema_name`. For example, both `news_story` and `government_response` types would have the group `news_article`.",
          "enum": [
            "news_article"
          ]
        },
        "publishing_api_schema_name": {
          "type": "string",
          "description": "Name of the schema in the Publishing API for this document type. Different types might share the same schema name. For example, `news_story` and `government_response` types both use the `news_article` schema.",
          "enum": [
            "history",
            "topical_event",
            "news_article",
            "case_study",
            "mini_site"
          ]
        },
        "publishing_api_document_type": {
          "type": "string",
          "description": "Document type name in the Publishing API.",
          "enum": [
            "government_response",
            "news_story",
            "press_release",
            "world_news_story",
            "history",
            "topical_event",
            "case_study",
            "mini_site_landing",
            "mini_site_child"
          ]
        },
        "rendering_app": {
          "type": "string",
          "description": "The frontend application responsible for rendering this document type.",
          "enum": [
            "frontend",
            "collections"
          ]
        },
        "images": {
          "type": "object",
          "description": "Whether users can upload images for this document type. When enabled, it renders the Images tab.",
          "properties": {
            "enabled": {
              "type": "boolean",
              "description": "Whether users can upload images for this document type. When enabled, it renders the Images tab."
            },
            "usages": {
              "type": "object",
              "patternProperties": {
                ".*": {
                  "type": "object",
                  "required": ["kinds", "multiple", "caption_enabled"],
                  "properties": {
                    "label": {
                      "type": "string",
                      "description": "The human-friendly label for the usage"
                    },
                    "multiple": {
                      "type": "boolean",
                      "description": "Whether users can upload multiple images of this image kind"
                    },
                    "caption_enabled": {
                      "type": "boolean",
                      "description": "Whether the caption field is shown for this image usage. Defaults to true if not specified."
                    },
                    "kinds": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "description": "The name of the image kind",
                        "enum": [
                          "default",
                          "topical_event_logo",
                          "topical_event_header"
                        ]
                      },
                      "minLength": 1,
                      "additionalProperties": false
                    }
                  }
                }
              },
              "propertyNames": {
                "enum": [
                  "govspeak_embed",
                  "header",
                  "logo",
                  "sidebar",
                  "lead"
                ]
              },
              "minLength": 1,
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "send_change_history": {
          "type": "boolean",
          "description": "Whether to send change history to the Publishing API. The change history will allow users to see major change updates to the document. Most editionable types should have this enabled."
        },
        "organisations": {
          "type": ["array", "null"],
          "description": "Array of organisation content IDs allowed to use this type, or null to allow all organisations.",
          "items": {
            "type": "string"
          }
        },
        "backdating_enabled": {
          "type": "boolean",
          "description": "Whether backdating is allowed for this document type. This is required for documents representing past printed papers or documents from other digital sources outside Whitehall."
        },
        "history_mode_enabled": {
          "type": "boolean",
          "description": "Whether history mode is enabled for this document type. This controls whether the document can be marked as political."
        },
        "file_attachments_enabled": {
          "type": "boolean",
          "description": "Whether file attachments are allowed for this document type. When enabled, it renders the Attachments tab."
        },
        "taxon": {
          "type": "object",
          "properties": {
            "required": {
              "type": "boolean",
              "description": "Whether a taxon is required for this document type."
            },
            "enabled": {
              "type": "boolean",
              "description": "Whether a taxon can be set for this document type."
            }
          }
        },
        "translations_enabled": {
          "type": "boolean",
          "description": "Whether translations are supported for this document type."
        },
        "allowed_child_document_types": {
          "type": "array",
          "description": "Document types that are permitted to be created as children of this document type. Defaults to no allowed child types.",
          "items": {
            "type": "object",
            "properties": {
              "document_type": {
                "type": "string",
                "description": "The `key` of a configurable document type that is allowed to be created as a child of this document type."
              }
            },
            "required": ["document_type"],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "base_path_prefix",
        "publishing_api_schema_name",
        "publishing_api_document_type",
        "rendering_app",
        "images",
        "send_change_history",
        "organisations",
        "backdating_enabled",
        "history_mode_enabled",
        "file_attachments_enabled",
        "taxon",
        "translations_enabled"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "key",
    "schema",
    "forms",
    "presenters",
    "settings",
    "title",
    "description"
  ],
  "if": {
    "properties": {
      "settings": {
        "properties": {
          "images": {
            "properties": {
              "enabled": { "const": false }
            }
          }
        }
      }
    }
  },
  "then": {
    "properties": {
      "forms": {
        "properties": {
          "images": {
            "maxProperties": 0,
            "x-error": {
              "maxProperties": "forms/images cannot be defined if settings/images/enabled is `false`"
            }
          }
        }
      }
    }
  }
}

=== alphagov/whitehall/app/models/configurable_document_types/topical_event.json
{
  "key": "topical_event",
  "title": "Topical event",
  "description": "Use this to communicate government activity about high-profile events or in response to a major crisis. You must get approval from GDS before creating one.",
  "forms": {
    "documents": {
      "fields": {
        "body": {
          "title": "Body",
          "description": "The main content of the page",
          "required": true,
          "block": "govspeak",
          "attribute_path": ["block_content", "body"],
          "translatable": true
        },
        "lead_organisations": {
          "title": "Lead organisations",
          "block": "ordered_select_with_search_tagging",
          "container": "organisations",
          "attribute_path": ["lead_organisation_ids"],
          "size": 4,
          "translatable": false
        },
        "supporting_organisations": {
          "title": "Supporting organisations",
          "block": "select_with_search_tagging",
          "container": "organisations",
          "attribute_path": ["supporting_organisation_ids"],
          "translatable": false
        }
      }
    },
    "social_media_accounts": {
      "dynamic": true,
      "label": "Social media accounts",
      "fields": {
        "social_media_links": {
          "title": "Social media accounts",
          "block": "default_array",
          "add_another_button_text": "Add a social media account", 
          "attribute_path": ["block_content", "social_media_links"],
          "translatable": true,
          "fields": {
            "social_media_service_name": {
              "title": "Channel",
              "block": "default_select",
              "attribute_path": ["social_media_service_name"],
              "blank_option_label": "Select channel",
              "translatable": true,
              "options": [
                {
                  "label": "X",
                  "value": "X"
                },
                {
                  "label": "Facebook",
                  "value": "Facebook"
                },
                {
                  "label": "YouTube",
                  "value": "YouTube"
                },
                {
                  "label": "Flickr",
                  "value": "Flickr"
                },
                {
                  "label": "Blog",
                  "value": "Blog"
                },
                {
                  "label": "Pinterest",
                  "value": "Pinterest"
                },
                {
                  "label": "LinkedIn",
                  "value": "LinkedIn"
                },
                {
                  "label": "Google Plus",
                  "value": "Google Plus"
                },
                {
                  "label": "Foursquare",
                  "value": "Foursquare"
                },
                {
                  "label": "Email",
                  "value": "Email"
                },
                {
                  "label": "Instagram",
                  "value": "Instagram"
                },
                {
                  "label": "Bluesky",
                  "value": "Bluesky"
                },
                {
                  "label": "Threads",
                  "value": "Threads"
                },
                {
                  "label": "Other",
                  "value": "Other"
                }
              ]
            },
            "title": {
              "title": "Title",
              "block": "default_string",
              "attribute_path": ["title"],
              "translatable": true
            },
            "url": {
              "title": "URL",
              "block": "default_string",
              "attribute_path": ["url"],
              "translatable": true
            }
          }
        }
      }
    }
  },
  "schema": {
    "attributes": {
      "body": {
        "type": "string"
      },
      "social_media_links": {
        "type": "array",
        "attributes": {
          "social_media_service_name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      }
    },
    "validations": {
      "presence": {
        "attributes": ["body"]
      },
      "length": {
        "attributes": ["body"],
        "maximum": 16777215
      },
      "safe_html": {
        "attributes": ["body"]
      },
      "no_footnotes_allowed": {
        "attributes": ["body"]
      },
      "embedded_contacts_exist": {
        "attributes": ["body"],
        "on": "publish"
      },
      "social_media_links": {
        "attributes": ["social_media_links"],
        "fields": {
          "service_field": "social_media_service_name",
          "url_field": "url",
          "title_field": "title"
        }
      }
    }
  },
  "presenters": {
    "publishing_api": {
      "details": {
        "body": "govspeak",
        "social_media_links": "social_media_links"
      },
      "links": [
        "organisations"
      ]
    }
  },
  "settings": {
    "base_path_prefix": "/government/topical-events",
    "publishing_api_schema_name": "topical_event",
    "publishing_api_document_type": "topical_event",
    "rendering_app": "frontend",
    "foo": "bar",
    "images": {
      "enabled": true,
      "usages": {
        "header": {
          "kinds": ["topical_event_header"],
          "multiple": false,
          "caption_enabled": true
        },
        "logo": {
          "label": "event logo",
          "kinds": ["topical_event_logo"],
          "multiple": false,
          "caption_enabled": false
        }
      }
    },
    "send_change_history": false,
    "file_attachments_enabled": false,
    "features_enabled": true,
    "organisations": null,
    "backdating_enabled": false,
    "history_mode_enabled": false,
    "taxon": {
      "enabled": true,
      "required": false
    },
    "translations_enabled": false
  }
}

=== alphagov/whitehall/app/models/configurable_document_types/case_study.json
{
  "key": "case_study",
  "title": "Case study",
  "description": "Use this to share real examples that help users understand a process or an important aspect of government policy covered on GOV.UK.",
  "forms": {
    "documents": {
      "fields": {
        "body": {
          "title": "Body",
          "description": "The main content of the page",
          "required": true,
          "block": "govspeak",
          "attribute_path": ["block_content", "body"],
          "translatable": true
        },
        "worldwide_organisations": {
          "title": "Worldwide organisations",
          "block": "select_with_search_tagging",
          "container": "worldwide_organisations",
          "attribute_path": ["worldwide_organisation_document_ids"],
          "translatable": false
        },
        "world_locations": {
          "title": "World locations",
          "block": "select_with_search_tagging",
          "container": "world_locations",
          "attribute_path": ["world_location_ids"],
          "translatable": false
        },
        "lead_organisations": {
          "title": "Lead organisations",
          "required": true,
          "block": "ordered_select_with_search_tagging",
          "container": "organisations",
          "attribute_path": ["lead_organisation_ids"],
          "size": 4,
          "translatable": false
        },
        "supporting_organisations": {
          "title": "Supporting organisations",
          "block": "select_with_search_tagging",
          "container": "organisations",
          "attribute_path": ["supporting_organisation_ids"],
          "translatable": false
        }
      }
    }
  },
  "schema": {
    "attributes": {
      "body": {
        "type": "string"
      }
    },
    "validations": {
      "presence": {
        "attributes": ["body"]
      },
      "length": {
        "attributes": ["body"],
        "maximum": 16777215
      },
      "safe_html": {
        "attributes": ["body"]
      },
      "no_footnotes_allowed": {
        "attributes": ["body"]
      },
      "embedded_contacts_exist": {
        "attributes": ["body"],
        "on": "publish"
      }
    }
  },
  "presenters": {
    "publishing_api": {
      "details": {
        "body": { "field": "body", "type": "compiled_govspeak" }
      },
      "links": [
        "world_locations",
        "organisations",
        "worldwide_organisations",
        "government"
      ]
    }
  },
  "settings": {
    "base_path_prefix": "/government/case-studies",
    "publishing_api_schema_name": "case_study",
    "publishing_api_document_type": "case_study",
    "rendering_app": "frontend",
    "images": {
      "enabled": true,
      "usages": {
        "govspeak_embed": {
          "kinds": ["default"],
          "multiple": true,
          "caption_enabled": true
        },        
        "lead": {
          "kinds": ["default"],
          "multiple": false,
          "caption_enabled": true
        }
      }
    },
    "send_change_history": true,
    "file_attachments_enabled": true,
    "organisations": null,
    "backdating_enabled": true,
    "history_mode_enabled": true,
    "taxon": {
      "enabled": true,
      "required": true
    },
    "translations_enabled": true
  }
}
